spring:
  application:
    name: aodun-eureka-server


---
spring:
  profiles: server1

server:
  port: 10001

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
#    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:10002/eureka/,http://${spring.cloud.client.ipAddress}:10003/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000


---
spring:
  profiles: server2

server:
  port: 1002

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
#    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:1001/eureka/,http://${spring.cloud.client.ipAddress}:1003/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
---
spring:
  profiles: server3

server:
  port: 1003

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
#    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:1002/eureka/,http://${spring.cloud.client.ipAddress}:1001/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000